language: python
python:
        - "3.6"

install:
        pip install pytest codecov
script:
        - coverage run test_wallet.py
        - coverage run test_capitalize.py
after_success:
        - codecov
