language: python

install:
        pip install pytest pytest-cov codecov
script:
        - pytest --cov-report term --cov=./
       
env: 
        - CODECOV_TOKEN=6585d92a-7916-4942-a727-b3d31ca51fca

after_success:
        - codecov
