language: python
python:
        - "3.6"
install:
        pip install pytest codecov
script:
        - pytest
        
env:
        - CODECOV_TOKEN="6585d92a-7916-4942-a727-b3d31ca51fca"
       
after_success:
        - codecov
