language: python
python:
        - "3.6"

install:
        pip install pytest pytest-cov
script:
        - pytest --cov-report xml --cov=./
after_success:
        - bash <(curl -s https://codecov.io/bash)
